// Autogenerated file - DO NOT EDIT!
"set platform pokitto";
"addSysCall setFPS setPen setFont setLED setTexture";
"addSysCall setMirrored setFlipped setTransparent";
"addSysCall setTileMap getTileProperty scanTileMap";
"addSysCall getWidth getHeight readByte getTime";
"addSysCall clear image text rect";
"push globals UP DOWN LEFT RIGHT A B C D FRAMETIME CAMERA_X CAMERA_Y PI HALF_PI TWO_PI";
"registerBuiltinResource fontMini fontTIC806x6 fontZXSpec fontAdventurer fontDonut fontDragon fontC64 fntC64UIGfx fontMonkey fontKarateka fontKoubit fontRunes fontTight fontTiny";
"include /source/main.js"
